version: '3.8'

services:
  frontend:
    build: ./frontend
    command: sh -c "npm install --force && npm run prod"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    command: sh -c "npm install && npm run build && npm run prod"
    depends_on:
      - database

  nginx_back:
    build: ./nginx_back
    ports:
      - "8000:80"
    depends_on:
      - backend




