version: '3.8'

services:
  frontend:
    build: ./frontend
    command: npm run prod

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    command: npm run prod

  nginx_back:
    build: ./nginx_back
    ports:
      - "8000:80"
    depends_on:
      - backend




