version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: npm run dev