version: '3.8'

services:
  frontend:
    build: ./frontend
    command: sh -c "npm install --force && npm run dev"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: sh -c "npm install && npm run dev"
    depends_on:
      - database