version: '3.8'

services:
  frontend:
    build: ./frontend
    command: npm install --force

  backend:
    build:
      context: ./backend
      dockerfile: frontend/Dockerfile
    command: npm install